M48
; DRILL file {KiCad 9.0.8} date 2026-03-28T18:05:22-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-28T18:05:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.010
%
G90
G05
T1
X173.482Y-70.104
X173.482Y-111.252
T2
X142.113Y-89.027
X142.113Y-110.617
M30
