M48
; DRILL file {KiCad 9.0.6} date 2026-03-29T22:52:31-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-29T22:52:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.490
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X105.41Y-88.9
X105.41Y-110.49
T2
X111.63Y-50.96
X111.63Y-70.96
T3
X118.11Y-40.64
X118.11Y-110.49
X173.99Y-40.64
X173.99Y-96.52
M30
